### ISSUE TITLE
Issues from The Team 132 cookieMonsters

### ISSUE THREAD

**Issue by Prabhakarzx** [digitekh2i/embeded-video-project#8]
### Here are few improvements required to make the project up-to the mark!

- Use text elements for all the text in the page, don't just put screenshots.
- Use keep different sections separate and it will help you to track and build it.
- Additionally you can use border-style element to check which section is taking how much space.
- Add images in the folder and link them.
- You can also install some extentions in VSCode for making it easier, if not already.

Hope it helps, Thanks!

**Comment by nrqrmz** [comment]
Hi Daniel

I recommend you to work with the space between the video and your sidebar.
I would also recommend to add a subscribe button.
